apiVersion: v1
kind: Service
metadata:
  name: shiori-service-lb
  namespace: production
spec:
  selector:
    app: shiori
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer