kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-binding
  namespace: production
subjects:
  - kind: User
    name: leonardo
    apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""