apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  claimRef:
    name: data-es-cluster-0
    namespace: monitoring