apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: devops-tools
spec:
  containers:
  - name: test-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "ping 10.110.191.87 -c 10"]
