apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibGVvbmFyZG9wb2dnaWFuaSIsInBhc3N3b3JkIjoiZ2hwX05JYlZCSWJyYVFqYTNIMEVrcE11QXoyVXdWQWJuSjNkazJDaSIsImVtYWlsIjoibGVvbmFyZG8ucG9nZ2lhbmlAZ21haWwuY29tIiwiYXV0aCI6ImJHVnZibUZ5Wkc5d2IyZG5hV0Z1YVRwbmFIQmZUa2xpVmtKSlluSmhVV3BoTTBnd1JXdHdUWFZCZWpKVmQxWkJZbTVLTTJSck1rTnAifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
